export const IMPORT_CSV_BILL = "IMPORT_CSV_BILL" 
export const IMPORT_CSV_CATEGORY = "IMPORT_CSV_CATEGORY" 
export const ADD_BILL = "ADD_BILL"

export const SET_MONTH_FILTER = "SET_MONTH_FILTER"
export const SET_CATEGORY_FILTER = "SET_CATEGORY_FILTER"

